#!/bin/bash
# Hellboy
IP=$1 && shift
SESSION=$1 && shift
COURSE=$1 && shift
GROUP=$1 && shift
TA=$1 && shift
TA_GROUP=$1 && shift
DESC=$1 && shift

ENDPOINT=https://$IP
URL="${ENDPOINT}/aportal/regadm/student.portal/student.portal.jsp?action=apply_reg&st_info=add"

ID="${COURSE}_${GROUP}_${TA}_${TA_GROUP}"
echo "Starting loop for $ID"

while [ true ] ; do

R=`curl -s --insecure \
     --cookie "JSESSIONID=${SESSION}" \
     -X POST \
     --data "st_reg_course=${ID}" \
     $URL | grep frmtrc`

echo "`date +"%D %T"` $DESC $R"

sleep 1
done
