#!/bin/bash
# Hellboy
set -e

LIST_FILE=$1
IP=$2
SESSION=$3

while read l ;do
    echo $l
    echo ./loop $IP $SESSION $l | bash &
done < $LIST_FILE

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
sleep infinity
